### ISSUE TITLE
Allow prefix for CSS class name

### ISSUE THREAD

**Issue by bolinfest** [azukaar/electron-css#1]
I've read https://itnext.io/stop-using-css-in-js-and-welcome-proper-styling-in-js-with-electron-css-d28536ba3e85 and I can see the motivation for randomly generated class names, but they are very hard to work with when debugging in the DOM inspector.

I would be nice if `CSS` took an optional prefix or some sort of pattern that was embedded into the random string so it was easier to map back to your code. `class1543956215536` is not particularly present to work with and the number of digits seems excessive. Why not use an incrementing counter instead of random numbers?

**Comment by bolinfest** [comment]
Or even just let me name it explicitly:

```js
const wide = CSS('wide-char', {
  display: "inline-block",
  width: "20px"
});
```

and the value of `wide` would be `"wide-char"`.

**Comment by mbret** [comment]
Being able to prefix / suffix your class as
`const wide = CSS('wide-char', {});`
-> `'class12564-wide-char'`

Seems to be a good idea indeed

**Comment by azukaar** [comment]
Supported from 0.14.0 as :

```
const wide = CSS({}, 'myclassname');
```
